import { neon } from "@neondatabase/serverless";
import Database from "better-sqlite3";
import { mkdirSync } from "node:fs";
import { join } from "node:path";

type DatabaseValue = string | number | boolean | null;

type DatabaseClient = {
  query<Row>(statement: string, values?: DatabaseValue[]): Promise<Row[]>;
  execute(statement: string, values?: DatabaseValue[]): Promise<void>;
};

export const postgresConnectionString =
  process.env.POSTGRES_URL ?? process.env.DATABASE_URL;

const sqliteSchema = `
  CREATE TABLE IF NOT EXISTS people (id INTEGER PRIMARY KEY, display_name TEXT NOT NULL, archived INTEGER NOT NULL DEFAULT 0);
  CREATE UNIQUE INDEX IF NOT EXISTS active_person_name ON people(display_name) WHERE archived = 0;
  CREATE TABLE IF NOT EXISTS lunch_days (id INTEGER PRIMARY KEY, date TEXT NOT NULL UNIQUE, parcel_capacity INTEGER NOT NULL DEFAULT 2, final_parcel_order INTEGER, order_needs_reconfirmation INTEGER NOT NULL DEFAULT 0);
  CREATE TABLE IF NOT EXISTS attendance (lunch_day_id INTEGER NOT NULL REFERENCES lunch_days(id) ON DELETE CASCADE, person_id INTEGER NOT NULL REFERENCES people(id), attending INTEGER NOT NULL, brings_home_food INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (lunch_day_id, person_id));
  CREATE TABLE IF NOT EXISTS charges (id INTEGER PRIMARY KEY, lunch_day_id INTEGER NOT NULL REFERENCES lunch_days(id) ON DELETE CASCADE, person_id INTEGER NOT NULL REFERENCES people(id), display_name TEXT NOT NULL, amount INTEGER NOT NULL CHECK (amount >= 0), paid INTEGER NOT NULL DEFAULT 0, UNIQUE (lunch_day_id, person_id));
  CREATE TABLE IF NOT EXISTS group_overrides (lunch_day_id INTEGER NOT NULL REFERENCES lunch_days(id) ON DELETE CASCADE, person_id INTEGER NOT NULL REFERENCES people(id), group_number INTEGER NOT NULL, PRIMARY KEY (lunch_day_id, person_id));
`;

const postgresSchema = `
  CREATE TABLE IF NOT EXISTS people (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, display_name TEXT NOT NULL, archived INTEGER NOT NULL DEFAULT 0);
  CREATE UNIQUE INDEX IF NOT EXISTS active_person_name ON people(display_name) WHERE archived = 0;
  CREATE TABLE IF NOT EXISTS lunch_days (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date TEXT NOT NULL UNIQUE, parcel_capacity INTEGER NOT NULL DEFAULT 2, final_parcel_order INTEGER, order_needs_reconfirmation INTEGER NOT NULL DEFAULT 0);
  CREATE TABLE IF NOT EXISTS attendance (lunch_day_id BIGINT NOT NULL REFERENCES lunch_days(id) ON DELETE CASCADE, person_id BIGINT NOT NULL REFERENCES people(id), attending INTEGER NOT NULL, brings_home_food INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (lunch_day_id, person_id));
  CREATE TABLE IF NOT EXISTS charges (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lunch_day_id BIGINT NOT NULL REFERENCES lunch_days(id) ON DELETE CASCADE, person_id BIGINT NOT NULL REFERENCES people(id), display_name TEXT NOT NULL, amount INTEGER NOT NULL CHECK (amount >= 0), paid INTEGER NOT NULL DEFAULT 0, UNIQUE (lunch_day_id, person_id));
  CREATE TABLE IF NOT EXISTS group_overrides (lunch_day_id BIGINT NOT NULL REFERENCES lunch_days(id) ON DELETE CASCADE, person_id BIGINT NOT NULL REFERENCES people(id), group_number INTEGER NOT NULL, PRIMARY KEY (lunch_day_id, person_id));
`;

const createSqliteClient = (): DatabaseClient => {
  const dataDirectory =
    process.env.LUNCH_DATA_DIR ?? join(process.cwd(), "data");
  mkdirSync(dataDirectory, { recursive: true });
  const sqlite = new Database(join(dataDirectory, "lunch-ledger.sqlite"));
  sqlite.pragma("foreign_keys = ON");
  sqlite.exec(sqliteSchema);

  return {
    async query<Row>(statement: string, values: DatabaseValue[] = []) {
      return sqlite
        .prepare(statement.replace(/\$\d+/g, "?"))
        .all(...values) as Row[];
    },
    async execute(statement: string, values: DatabaseValue[] = []) {
      sqlite.prepare(statement.replace(/\$\d+/g, "?")).run(...values);
    },
  };
};

const createPostgresClient = (connectionString: string): DatabaseClient => {
  const sql = neon(connectionString);
  return {
    async query<Row>(statement: string, values: DatabaseValue[] = []) {
      return (await sql.query(statement, values)) as Row[];
    },
    async execute(statement: string, values: DatabaseValue[] = []) {
      await sql.query(statement, values);
    },
  };
};

export const database = postgresConnectionString
  ? createPostgresClient(postgresConnectionString)
  : createSqliteClient();

export const databaseReady = postgresConnectionString
  ? postgresSchema
      .split(";")
      .filter((statement) => statement.trim())
      .reduce(
        (ready, statement) => ready.then(() => database.execute(statement)),
        Promise.resolve(),
      )
  : Promise.resolve();
